name: spectra

services:
  postgres:
    image: postgres:18-alpine3.24
    container_name: spectra-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - pg_data:/var/lib/postgresql
      - ./docker/backup:/backup:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg_data: